### ISSUE TITLE
GraphAligner install error

### ISSUE THREAD

**Issue by maxmaronna** [vgl-hub/gfalign#4]
Hello Giulio,
I am trying to install gfalign but It seems something is not working properly (A conda env named GraphAligner was created but no software is installed; see below my full command line for details).
Thanks in advance!
max
PD I think it would be useful to detail that users need to have installed anaconda (or similar) in our systems. 
PD2 I don´t know why github is strikethrough part of my text...
--
maxmaronna@access2:~/01-SOFTWARE$ git clone https://github.com/vgl-hub/gfalign.git --recursive
Cloning into 'gfalign'...
remote: Enumerating objects: 333, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 333 (delta 19), reused 18 (delta 8), pack-reused 298
Receiving objects: 100% (333/333), 54.29 KiB | 1.51 MiB/s, done.
Resolving deltas: 100% (197/197), done.
Submodule 'GraphAligner' (https://github.com/maickrau/GraphAligner.git) registered for path 'GraphAligner'
Submodule 'gfalibs' (https://github.com/vgl-hub/gfalibs.git) registered for path 'gfalibs'
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner'...
remote: Enumerating objects: 5362, done.
remote: Counting objects: 100% (1119/1119), done.
remote: Compressing objects: 100% (290/290), done.
remote: Total 5362 (delta 858), reused 1080 (delta 829), pack-reused 4243
Receiving objects: 100% (5362/5362), 1.64 MiB | 7.01 MiB/s, done.
Resolving deltas: 100% (3914/3914), done.
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/gfalibs'...
remote: Enumerating objects: 2058, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 2058 (delta 189), reused 186 (delta 159), pack-reused 1783
Receiving objects: 100% (2058/2058), 3.02 MiB | 16.03 MiB/s, done.
Resolving deltas: 100% (1533/1533), done.
Submodule path 'GraphAligner': checked out '4e2ca66ad5a2c3551107e9d59f6f61b2a41683a2'
Submodule 'BBHash' (https://github.com/maickrau/BBHash.git) registered for path 'GraphAligner/BBHash'
Submodule 'MEMfinder' (https://github.com/maickrau/MEMfinder.git) registered for path 'GraphAligner/MEMfinder'
Submodule 'concurrentqueue' (https://github.com/cameron314/concurrentqueue.git) registered for path 'GraphAligner/concurrentqueue'
Submodule 'parallel-hashmap' (https://github.com/greg7mdp/parallel-hashmap.git) registered for path 'GraphAligner/parallel-hashmap'
Submodule 'zstr' (https://github.com/mateidavid/zstr.git) registered for path 'GraphAligner/zstr'
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner/BBHash'...
remote: Enumerating objects: 550, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 550 (delta 0), reused 1 (delta 0), pack-reused 547
Receiving objects: 100% (550/550), 237.08 KiB | 5.64 MiB/s, done.
Resolving deltas: 100% (319/319), done.
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner/MEMfinder'...
remote: Enumerating objects: 255, done.
remote: Counting objects: 100% (255/255), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 255 (delta 173), reused 188 (delta 107), pack-reused 0
Receiving objects: 100% (255/255), 57.28 KiB | 2.39 MiB/s, done.
Resolving deltas: 100% (173/173), done.
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner/concurrentqueue'...
remote: Enumerating objects: 4199, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4199 (delta 7), reused 11 (delta 7), pack-reused 4186
Receiving objects: 100% (4199/4199), 4.92 MiB | 15.65 MiB/s, done.
Resolving deltas: 100% (1538/1538), done.
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner/parallel-hashmap'...
remote: Enumerating objects: 3294, done.
remote: Counting objects: 100% (723/723), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 3294 (delta 578), reused 659 (delta 538), pack-reused 2571
Receiving objects: 100% (3294/3294), 3.06 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (2246/2246), done.
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner/zstr'...
remote: Enumerating objects: 470, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 470 (delta 134), reused 123 (delta 118), pack-reused 296
Receiving objects: 100% (470/470), 92.86 KiB | 2.90 MiB/s, done.
Resolving deltas: 100% (228/228), done.
Submodule path 'GraphAligner/BBHash': checked out '618b39f1849023677f70b3928075bddb642a8406'
Submodule path 'GraphAligner/MEMfinder': checked out '5009461554124fff79058a9225048ede9ac89e7b'
Submodule 'libsais' (https://github.com/IlyaGrebnov/libsais.git) registered for path 'GraphAligner/MEMfinder/libsais'
Cloning into '/home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner/MEMfinder/libsais'...
remote: Enumerating objects: 265, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 265 (delta 70), reused 80 (delta 48), pack-reused 152
Receiving objects: 100% (265/265), 287.06 KiB | 1.46 MiB/s, done.
Resolving deltas: 100% (161/161), done.
Submodule path 'GraphAligner/MEMfinder/libsais': checked out 'bca1eb2699eaf251e049f90ad3209044b7919ae7'
Submodule path 'GraphAligner/concurrentqueue': checked out '8f65a8734d77c3cc00d74c0532efca872931d3ce'
Submodule path 'GraphAligner/parallel-hashmap': checked out '7684faf186806e2c88554a78188c18185b21f127'
Submodule path 'GraphAligner/zstr': checked out '93cfe0a8cead9cdebe06ecff602baca5bd043abe'
Submodule path 'gfalibs': checked out '36ee6000b2d315d29cf4089852ba53e223768187'
maxmaronna@access2:~/01-SOFTWARE$ make -j gfalign/
make: Nothing to be done for 'gfalign/'.
maxmaronna@access2:~/01-SOFTWARE$ cd gfalign/
maxmaronna@access2:~/01-SOFTWARE/gfalign$ ll
total 32
drwxr-xr-x.  8 maxmaronna cnidaria 4096 May 13 14:39 ./
drwxr-xr-x. 17 maxmaronna cnidaria  318 May 13 14:39 ../
drwxr-xr-x.  4 maxmaronna cnidaria  120 May 13 14:39 gfalibs/
drwxr-xr-x.  9 maxmaronna cnidaria 4096 May 13 14:39 .git/
-rw-r--r--.  1 maxmaronna cnidaria 1670 May 13 14:39 .gitignore
-rw-r--r--.  1 maxmaronna cnidaria  226 May 13 14:39 .gitmodules
drwxr-xr-x. 11 maxmaronna cnidaria 4096 May 13 14:39 GraphAligner/
drwxr-xr-x.  2 maxmaronna cnidaria  109 May 13 14:39 include/
-rw-r--r--.  1 maxmaronna cnidaria 1064 May 13 14:39 LICENSE
-rw-r--r--.  1 maxmaronna cnidaria 2541 May 13 14:39 Makefile
-rw-r--r--.  1 maxmaronna cnidaria 1083 May 13 14:39 README.md
drwxr-xr-x.  2 maxmaronna cnidaria   97 May 13 14:39 src/
drwxr-xr-x.  2 maxmaronna cnidaria  182 May 13 14:39 testFiles/
maxmaronna@access2:~/01-SOFTWARE/gfalign$ make -j
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --base
mkdir -p build/bin/.o

usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --base
>>> Detected conda, but GraphAligner is missing in . Installing ...
make -j -C /home/maxmaronna/01-SOFTWARE/gfalign/gfalibs CXXFLAGS="-g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra"
make[1]: Entering directory '/home/maxmaronna/01-SOFTWARE/gfalign/gfalibs'
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/input-filters.cpp -o input-filters.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/input-gfa.cpp -o input-gfa.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/input-agp.cpp -o input-agp.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/gfa.cpp -o gfa.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/gfa-lines.cpp -o gfa-lines.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/log.cpp -o log.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/functions.cpp -o functions.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/bed.cpp -o bed.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/stream-obj.cpp -o stream-obj.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/uid-generator.cpp -o uid-generator.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/struct.cpp -o struct.o
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra  -c src/output.cpp -o output.o
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...make[1]: Leaving directory '/home/maxmaronna/01-SOFTWARE/gfalign/gfalibs'
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra -pthread -c src/main.cpp -o build/bin/.o/main
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra -pthread -c src/alignments.cpp -o build/bin/.o/alignments
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra -pthread -c src/input.cpp -o build/bin/.o/input
g++ -g --std=c++14 -O3 -I./include -Igfalibs/include -Wall -Wextra -pthread -c src/eval.cpp -o build/bin/.o/eval
............
Solving package specifications: .
ca-certificate 100% |#######################| Time: 0:00:00   7.98 MB/s
ld_impl_linux- 100% |######################| Time: 0:00:00  17.52 MB/s
libgcc-devel_l 100% |######################| Time: 0:00:00  37.07 MB/s
libgfortran5-1 100% |######################| Time: 0:00:00  35.47 MB/s
libprotobuf-st 100% |######################| Time: 0:00:00  37.57 MB/s
libstdcxx-deve 100% |######################| Time: 0:00:00  43.67 MB/s
libstdcxx-ng-1 100% |######################| Time: 0:00:00  37.52 MB/s
libgfortran-ng 100% |######################| Time: 0:00:00   2.21 MB/s
libgomp-11.2.0 100% |#####################| Time: 0:00:00  18.12 MB/s
_openmp_mutex- 100% |###################| Time: 0:00:00   2.48 MB/s
binutils_impl_ 100% |######################| Time: 0:00:00  39.51 MB/s
binutils_linux 100% |######################| Time: 0:00:00   3.07 MB/s
libgcc-ng-11.2 100% |#####################| Time: 0:00:00  29.72 MB/s
icu-58.2-hf484 100% |#####################| Time: 0:00:00  41.91 MB/s
jemalloc-5.2.0 100% |#####################| Time: 0:00:00  34.89 MB/s
libdivsufsort- 100% |######################| Time: 0:00:00   4.12 MB/s
libffi-3.4.2-h 100% |#######################| Time: 0:00:00   6.44 MB/s
libopenblas-0. 100% |#####################| Time: 0:00:00  41.11 MB/s
libsanitizer-1 100% |######################| Time: 0:00:00  40.29 MB/s
libzlib-1.2.11 100% |######################| Time: 0:00:00   4.49 MB/s
make-4.3-hd18e 100% |###################| Time: 0:00:00  20.02 MB/s
openssl-1.1.1n 100% |#####################| Time: 0:00:00  32.77 MB/s
pkg-config-0.2 100% |####################| Time: 0:00:00   8.91 MB/s
sdsl-lite-2.1. 100% |######################| Time: 0:00:00  24.64 MB/s
sparsehash-2.0 100% |####################| Time: 0:00:00   5.85 MB/s
xz-5.2.5-h5169 100% |####################| Time: 0:00:00  16.01 MB/s
gcc_impl_linux 100% |####################| Time: 0:00:01  43.98 MB/s
libblas-3.9.0- 100% |#####################| Time: 0:00:00 954.06 kB/s
readline-8.1-h 100% |####################| Time: 0:00:00  16.54 MB/s
tk-8.6.12-h278 100% |####################| Time: 0:00:00  22.29 MB/s
zlib-1.2.11-h1 100% |####################| Time: 0:00:00   7.42 MB/s
boost-cpp-1.67 100% |###################| Time: 0:00:00  37.04 MB/s
gcc_linux-64-1 100% |###################| Time: 0:00:00   3.17 MB/s
gxx_impl_linux 100% |###################| Time: 0:00:00  43.40 MB/s
libboost-1.67. 100% |####################| Time: 0:00:00  42.97 MB/s
libcblas-3.9.0 100% |####################| Time: 0:00:00   1.11 MB/s
liblapack-3.9. 100% |#####################| Time: 0:00:00   1.40 MB/s
libprotobuf-3. 100% |####################| Time: 0:00:00  34.15 MB/s
sqlite-3.38.2- 100% |#####################| Time: 0:00:00  23.50 MB/s
gxx_linux-64-1 100% |####################| Time: 0:00:00   2.40 MB/s
python-3.6.15- 100% |###################| Time: 0:00:00  44.12 MB/s
python_abi-3.6 100% |###################| Time: 0:00:00 391.64 kB/s
six-1.16.0-pyh 100% |####################| Time: 0:00:00   1.55 MB/s
wheel-0.37.1-p 100% |####################| Time: 0:00:00   2.41 MB/s
numpy-1.19.5-p 100% |###################| Time: 0:00:00  39.32 MB/s
setuptools-58. 100% |#####################| Time: 0:00:00  31.45 MB/s
boost-1.67.0-p 100% |####################| Time: 0:00:00  18.32 MB/s
pip-21.3.1-pyh 100% |####################| Time: 0:00:00  26.36 MB/s
protobuf-3.14. 100% |####################| Time: 0:00:00  18.31 MB/s
#
# To activate this environment, use:
# > source activate GraphAligner
#
# To deactivate an active environment, use:
# > source deactivate
#

usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --base
/bin/bash: line 2: /etc/profile.d/conda.sh: No such file or directory

CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?

CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?

mv: cannot stat 'GraphAligner/bin/*': No such file or directory
make: *** [Makefile:82: GraphAligner] Error 1

maxmaronna@access2:~/01-SOFTWARE/gfalign$ source activate GraphAligner/
(GraphAligner/) maxmaronna@access2:~/01-SOFTWARE/gfalign$ conda list
# packages in environment at /home/maxmaronna/01-SOFTWARE/gfalign/GraphAligner:
#

(GraphAligner/) maxmaronna@access2:~/01-SOFTWARE/gfalign$

**Comment by gf777** [comment]
I somehow missed this, sorry! Done
